Updated

diff --git a/build_image b/build_image
--- a/build_image
+++ b/build_image
@@ -1,14 +1,30 @@
+#!/bin/bash
+
+stty -echo
+
+# Make sure echo is turned back on even if there are failures
+trap 'stty echo' EXIT
+
+IMAGE_NAME=bhima/e2e-tests:v1
 
 # Update the BHIMA repo first
-pushd /home/bhima/builds/Bhima
+echo "Updating BHIMA repo"
+cp ./setup.bash Bhima/
+pushd /home/bhima/builds/Bhima >& /dev/null
 git pull
-# Temporarily modify the .dockerignore file to allow copying the 'test' directory
-sed -i '/^test/d' .dockerignore
-popd
 
-sudo docker build -f /home/bhima/builds/Dockerfile -t bhima/e2e-tests:v1 /home/bhima/builds/Bhima
+# Since we will be running tests, temporarily modify the .dockerignore
+# file to allow copying the 'test' directory
+sed -i '/^test/d' .dockerignore
+popd >& /dev/null
+
+echo "Building docker image $IMAGE_NAME"
+sudo docker build -f /home/bhima/builds/Dockerfile -t $IMAGE_NAME /home/bhima/builds/Bhima
 
 # Restore the .dockerignore file
-pushd /home/bhima/builds/Bhima
+echo "Cleaning up"
+pushd /home/bhima/builds/Bhima >& /dev/null
 git checkout .dockerignore
-popd
+popd >& /dev/null
+
+stty echo
